[package]
name = "elastic-tls"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "TLS Interface for ELASTIC project"

[dependencies]
wit-bindgen = "0.17"
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.24"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-native-certs = "0.6.3"
rustls-pemfile = "1.0"
thiserror = "1.0"
tracing = "0.1"
async-trait = "0.1"
futures = "0.3"
webpki-roots = "0.25"

[dev-dependencies]
tokio-test = "0.4"
anyhow = "1.0"
tempfile = "3.8.1" 