[workspace]
members = [
    "crates/elastic-clock",
    "crates/elastic-crypto",
    "crates/elastic-file",
    "crates/elastic-tls"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "ELASTIC project workspace" 