[package]
name = "elastic"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = "0.11.0"
aes-gcm = "0.10.3"
rand = "0.8.5"
rsa = { version = "0.9.6", features = ["sha2", "pem"] }
pkcs8 = { version = "0.10.2", features = ["pem"] }
sha2 = "0.10.8"
hmac = { version = "0.12.1", features = ["std"] }
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.8.1" 