[package]
name = "wasm-crypto-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
elastic-crypto = { path = "../../crates/elastic-crypto" }
rand = "0.8"
hex = "0.4"
getrandom = { version = "0.2", features = ["js"] } 