[package]
name = "wasm-crypto-example"
version = "0.1.0"
edition = "2021"

[dependencies]
elastic-crypto = { path = "../../crates/elastic-crypto", features = ["wasm", "sevsnp"] }
wasm-bindgen = "0.2"
rand = "0.8"
hex = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasi = "0.11" 