[package]
name = "wasm-clock-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
elastic-clock = { path = "/home/ubuntu/elastic/crates/elastic-clock", default-features = false, features = ["linux"] }
