[package]
name = "wasm-clock-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasm_clock_example"
path = "src/main.rs"

[dependencies]
elastic-clock = { path = "../../crates/elastic-clock", default-features = false, features = ["linux"] }
