[package]
name = "elastic-crypto"
version = "0.1.0"
edition = "2021"
authors = ["ELASTIC Team"]
description = "Cryptographic operations implementation for ELASTIC project"

[dependencies]
aes-gcm = "0.10"
rand = "0.8"
thiserror = "1.0"
hex = "0.4"

[dev-dependencies]
anyhow = "1.0"
tempfile = "3.2"

[features]
default = ["linux"]
linux = []
wasm = [] 