[package]
name = "elastic-crypto"
version = "0.1.0"
edition = "2021"
authors = ["ELASTIC Team"]
description = "Cryptographic operations implementation for ELASTIC project"

[dependencies]
wit-bindgen = "0.41.0"
thiserror = "1.0"
libc = { version = "0.2", optional = true }
aes-gcm = "0.10"
rand = { version = "0.8", features = ["getrandom"] }
sha2 = "0.10"
hmac = "0.12"
base64 = "0.21"
getrandom = { version = "0.2", features = ["js", "wasm-bindgen"] }
ring = { version = "0.17", optional = true }
rsa = { version = "0.9", optional = true }

[dev-dependencies]
anyhow = "1.0"
tempfile = "3.2"

[features]
default = ["linux"]
linux = ["ring", "rsa", "libc"]
sev = []
wasm = ["getrandom/js", "getrandom/wasm-bindgen"] 